blog/urls.py
# coding=UTF-8

from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^index/$', views.index),  # 斜杠不能少
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)$', views.edit_page, name='edit_page'),
    url(r'^edit/action/$', views.edit_action, name='edit_action'),
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(null=True)

    def __str__(self):
        return self.title

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from . import models

def index(request):
    # article = models.Article.objects.get(pk=1)
    articles = models.Article.objects.all()
    return render(request, 'index.html', {
        'articles': articles
    })

def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'article_page.html', {'article': article})

def edit_page(request, article_id):
    if str(article_id) == '0':  # 新建文章
        return render(request, 'edit_page.html')

    # 修改文章
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'edit_page.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title', 'Title')  # Title是给一个默认值
    content = request.POST.get('content', 'Content')  # Content是给一个默认值
    article_id = request.POST.get('article_id', '0')  # Content是给一个默认值

    if article_id == '0':   # 新建文章
        models.Article.objects.create(title=title, content=content)
        return HttpResponseRedirect('/blog/index/')

    # 修改文章
    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    return HttpResponseRedirect('/blog/index/')

blog/templates/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
<h4>{{ article.title }}</h4>
<br>
<div>{{ article.content }}</div>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

blog/templates/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="article_id" value="{{ article.id | default:'0'}}">
    <div><label for="">文章标题：<input type="text" name="title" value="{{ article.title }}"></label></div>
    <br>
    <div><label for="">文章内容：<textarea name="content" cols="30" rows="10">{{ article.content }}</textarea></label></div>
    <br>
    <div><input type="submit" value="提交"></div>
</form>
</body>
</html>

blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
<h4>博客列表</h4>
<p><a href="{% url 'blog:edit_page' 0 %}">新文章</a></p>
{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a><br>
{% endfor %}
</body>
</html>